"""Audio storage service for managing temporary audio files."""

import asyncio
from datetime import datetime
from pathlib import Path


class AudioStorageService:
    """Service for managing temporary storage of generated audio files.

    This service handles the creation, naming, and automatic cleanup of
    temporary audio files generated by the TTS system. Files are stored
    with timestamped names and automatically deleted after a configurable delay.

    Attributes:
        temp_dir: Path to the temporary directory for audio files.
    """

    def __init__(self, temp_dir: Path | None = None) -> None:
        """Initialize the audio storage service.

        Args:
            temp_dir: Optional path to temporary directory. If None, defaults to
                     /tmp/mytts_audio. The directory will be created if it doesn't exist.
        """
        self.temp_dir = temp_dir or Path("/tmp/mytts_audio")
        self.temp_dir.mkdir(parents=True, exist_ok=True)

    def generate_filename(self) -> str:
        """Generate a timestamped filename for an audio file.

        Creates a filename in the format: mytts-YYYY-MM-DD-HHMMSS.mp3
        using the current UTC timestamp.

        Returns:
            A string containing the generated filename.

        Example:
            >>> service.generate_filename()
            'mytts-2025-11-24-143022.mp3'
        """
        timestamp = datetime.utcnow().strftime("%Y-%m-%d-%H%M%S")
        return f"mytts-{timestamp}.mp3"

    def get_temp_path(self, filename: str) -> Path:
        """Get the full path to a temporary file.

        Args:
            filename: The name of the file (e.g., from generate_filename()).

        Returns:
            A Path object representing the full path to the file in the temp directory.

        Example:
            >>> service.get_temp_path("mytts-2025-11-24-143022.mp3")
            PosixPath('/tmp/mytts_audio/mytts-2025-11-24-143022.mp3')
        """
        return self.temp_dir / filename

    async def schedule_cleanup(
        self,
        file_path: Path,
        delay_seconds: int = 300
    ) -> None:
        """Schedule automatic deletion of a file after a delay.

        This method asynchronously waits for the specified delay, then deletes
        the file. The deletion is performed in a thread pool to avoid blocking
        the async event loop. If the file doesn't exist at cleanup time, no
        error is raised.

        Args:
            file_path: Path to the file to delete.
            delay_seconds: Number of seconds to wait before deletion.
                          Defaults to 300 (5 minutes).

        Note:
            This method should be scheduled as a background task, not awaited
            directly in request handlers to avoid blocking responses.

        Example:
            >>> await service.schedule_cleanup(Path("/tmp/mytts_audio/file.mp3"))
        """
        await asyncio.sleep(delay_seconds)
        await asyncio.to_thread(file_path.unlink, missing_ok=True)
